version: "3.9"
services:
  app:
    image: dvbridges/birdpedia:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - pgadmin
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    container_name: "postgresql"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
  pgadmin:
    image: dpage/pgadmin4:4.29
    ports:
      - 5050:80
    environment:
      - name=value
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=test1234
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: